### ISSUE TITLE
Include compression with AEC

### ISSUE THREAD

**Issue by Try2Code** [conda-forge/eccodes-feedstock#55]
**Issue: Include compression with patent-free SZIP replacement libaec**

Hi!
With high-resolution datasets compression becomes a more general usecase. Unfortunately the eccodes package in conda does not support this. 
Libaes (https://www.dkrz.de/redmine/projects/aec) is an implementation avoiding the license issues of szip, howver is fully szip-compliant. It's well tested by other ports ( https://github.com/macports/macports-ports/blob/master/science/ecCodes/Portfile, https://packages.debian.org/de/sid/libaec0,https://www.freshports.org/science/libaec) or tools like CDO (https://aur.archlinux.org/packages/cdo/, https://packages.debian.org/de/sid/cdo)

My wish is to get that dependency included in the conda-forge package of eccodes.

cheers
try2

**Comment by m214089** [comment]
One more for this request 👍

**Comment by ocefpaf** [comment]
I think I have a prototype for `libaec`. I'll check the license and put a PR to stage-recipes soon.

PS: I'm also asking NumFOCUS some legal advice regarding packaging `SZIP`.

**Comment by Try2Code** [comment]
@ocepaf i once read through the szip license because of a binary distribution of CDO. afaik it is allowed to distribute binaries, that can decode but encoding binaries are prohibited by its license.

**Comment by scopatz** [comment]
Can someone point me to an actual license, please?

**Comment by m214089** [comment]
To make things a bit more clear, because I had to deal for this with WMO (World Meteorological Organization, http://www.wmo.int):
1. There is a standard compression algorithm defined, which has been published and put forwarded by CCSDS (https://public.ccsds.org/default.aspx), a cooperation of Space Agencies.
2. This has been patented by NASA only in the US, but this patent has been released some years ago.
3. There has been an implementation called szip, which can be added to hdf5and can only be used for decoding  with out restrictions.
4. DKRZ (http://www.dkrz.de) as a consequence wrote a new implementation of the respective algorithm which can be used. This library has an intrface wrapper for the szip API.

The code needed is libaec:
https://gitlab.dkrz.de/k202009/libaec
The license:
https://gitlab.dkrz.de/k202009/libaec/blob/master/Copyright.txt

There is no need to take 
https://support.hdfgroup.org/doc_resource/SZIP/
as 
libaec is a full replacement for this library/implementation of the aforementioned algorithm.

**Comment by m214089** [comment]
I forgot: libaec can be linked to hdf5 too and replace szip and get rid of the prohibitive license.

**Comment by scopatz** [comment]
Oh then just use libaec :)

**Comment by Try2Code** [comment]
+1 @scopatz

**Comment by ocefpaf** [comment]
> Oh then just use libaec :)

If `lebaec` is preferred let's forget about szip :smile: 

(PR for `lebaec` coming soon... Hold on.)

**Comment by ocefpaf** [comment]
I'm kind of swamped at the day job, if someone can send a PR for `libaec` it would help us a lot.

**Comment by kmuehlbauer** [comment]
@Try2Code @guidocioni @m214089 @scopatz @ocefpaf

See https://github.com/conda-forge/staged-recipes/pull/7133. OSX and Win builds need to be added. Feel free to add (also to maintainers).

**Comment by kmuehlbauer** [comment]
@guidocioni Yes, do you happen to know, how this is enabled? PR is welcome.

**Comment by guidocioni** [comment]
No idea :) Maybe @Try2Code and @m214089 could jump in?

**Comment by kmuehlbauer** [comment]
-DENABLE_AEC=ON

**Comment by kmuehlbauer** [comment]
see #57

**Comment by guidocioni** [comment]
> see #57

Thanks for spending time on this. I have to do some heavy computation using cfgrib, eccodes and dask and this is the only missing piece :)

**Comment by kmuehlbauer** [comment]
@guidocioni Hope this get's in smoothly.

**Comment by kmuehlbauer** [comment]
@guidocioni With #57 merged the updated eccodes should be available in short time.

Please test, if everything is OK,  we can close this issue.

**Comment by guidocioni** [comment]
> @guidocioni With #57 merged the updated eccodes should be available in short time.
> 
> Please test, if everything is OK, we can close this issue.

Halli hallo, just did a quick read-in check on our machine after having installed the new eccodes version and it seems like everything's working fine. This is a really nice Sunday. 💃

**Comment by kmuehlbauer** [comment]
@guidocioni Great! Going to close this issue.
